export const environment = {
  ENVIRONMENT: 'DEVELOPMENT',
  KEYCLOAK_URL: 'https://auth.mf.platform',
  KEYCLOAK_REALM: 'master',
  KEYCLOAK_CLIENT: 'single-site-dashboard',
  MF_DASHBOARD_WEBSOCKET_URL: 'https://dev.mf.platform/dashboard/operation-websocket-svc',
  MF_DASHBOARD_WEBSOCKET_WS_URL: 'wss://dev.mf.platform/dashboard/operation-websocket-svc',
  MF_RPS_URL: 'https://mf.platform/tr-rps',
  MF_RTD_URL: 'https://dev.mf.platform/dashboard/rtd/api',
  MF_ORDERAPP_URL: 'https://dev.mf.platform/orderapp/api',
  MF_DASHBOARD_MIDDLEWARE_URL: 'https://mf.platform/dashboard/operation-api-svc',
  MAP_ACCESS_TOKEN: 'pk.eyJ1Ijoia2dsYXlrZ2xheSIsImEiOiJjamQxZGlwZnMwOG91MzRxcTdscXhmYjNvIn0.1Cfts_Qesd4LJlu3uyo2kQ',
  MAP_API_URL: 'https://api.mapbox.com/styles/v1/mapbox/dark-v9/tiles/256/{z}/{x}/{y}?access_token=',
  ROUTE_API_URL: 'https://api.mapbox.com/directions/v5/mapbox/cycling',
};
