export const RoutePaths = Object.freeze({
  BASE: '',
  HOME: 'factory',
  DEFAULT: 'modelfactory',
  FALLBACK: 'fallback',
  UNAUTHORIZED: 'unauthorized',
  LAYER: 'layer',
  LAYER_ONE: 'layer-one',
  LAYER_TWO: 'layer-two',
  LOGISTIC_TRACKING: 'logistic-tracking',
  MANAGEMENT_KPIS: 'management-kpis',
  DEMAND_PROFILE: 'demand-profile',
  PRODUCTION_TRACKING: 'production-tracking',
  PRODUCTION_INVENTORY: 'production-inventory',
  RESOURCE_TRACKING: 'resource-tracking',
  RESOURCE_HEALTH: 'resource-health',
});
