export const routePaths = {
  BASE: '',
  HOME: ':factory',
  DEFAULT: 'mf',
  FALLBACK: 'fallback',
  UNAUTHORIZED: 'unauthorized',
  LOGISTIC_TRACKING_ONE: 'logistic-tracking-one',
  LOGISTIC_TRACKING_TWO: 'logistic-tracking-two',
  MANAGEMENT_KPIS_ONE: 'management-kpis-one',
  MANAGEMENT_KPIS_TWO: 'management-kpis-two',
  DEMAND_PROFILE_ONE: 'demand-profile-one',
  DEMAND_PROFILE_TWO: 'demand-profile-two',
  PRODUCTION_TRACKING_ONE: 'production-tracking-one',
  PRODUCTION_TRACKING_TWO: 'production-tracking-two',
  PRODUCTION_INVENTORY_ONE: 'production-inventory-one',
  PRODUCTION_INVENTORY_TWO: 'production-inventory-two',
  RESOURCE_TRACKING_ONE: 'resource-tracking-one',
  RESOURCE_TRACKING_TWO: 'resource-tracking-two',
  RESOURCE_HEALTH_ONE: 'resource-health-one',
  RESOURCE_HEALTH_TWO: 'resource-health-two',
};
